{
   "sheetName" :"库存统计分析",
   "columns" :[{
      "fieldName" :"mcode",
      "columnName" :"物料编码"
   }, {
      "fieldName" :"mname",
      "columnName" :"物料名称"
   }, {
      "fieldName" :"model",
      "columnName" :"规格"
   }, {
      "fieldName" :"unit",
      "columnName" :"单位"
   }, {
      "fieldName" :"itemNo",
      "columnName" :"货号"
   }, {
      "fieldName" :"cateL1",
      "columnName" :"大类"
   }, {
      "fieldName" :"cateL2",
      "columnName" :"中类"
   }, {
      "fieldName" :"cateL3",
      "columnName" :"小类"
   }, {
      "fieldName" :"smanager",
      "columnName" :"库管员"
   }, {
      "fieldName" :"totalIn",
      "columnName" :"总入库数量"
   }, {
      "fieldName" :"totalOut",
      "columnName" :"总出库数量"
   }, {
      "fieldName" :"totalInNum",
      "columnName" :"总入库次数"
   }, {
      "fieldName" :"totalOutNum",
      "columnName" :"总出口次数"
   }, {
      "fieldName" :"storageMax",
      "columnName" :"最高库存总量"
   }, {
      "fieldName" :"storageHighNum",
      "columnName" :"高库存天数"
   }]
}